import type { Template } from "./types";

/** Exactly ten distinct, editable starting points. */
export const TEMPLATES: readonly Template[] = [
  { id: "someone-i-miss", theme: "Someone I miss", tagline: "Hold a person close for the length of a song", starterThought: "I miss someone whose absence still appears in ordinary moments—the songs they loved, the chair they used, and the things I still want to tell them.", feelings: ["nostalgic", "lonely", "grateful"], glyph: "◇", suggested: { genre: "Acoustic / Folk", mood: "Melancholy" } },
  { id: "starting-over", theme: "Starting over", tagline: "Step into a chapter that has not been written", starterThought: "I am beginning again, and I cannot tell whether the feeling in my chest is fear or hope. I want to remember this moment before the new life feels familiar.", feelings: ["anxious", "hopeful", "excited"], glyph: "↗", suggested: { genre: "Pop", mood: "Hopeful" } },
  { id: "something-unsaid", theme: "Something I never said", tagline: "Give words to what stayed quiet", starterThought: "There is something I never said when I had the chance. I have carried the sentence for so long that it has become part of me, and I am ready to let it speak.", feelings: ["tender", "anxious", "bittersweet"], glyph: "…", suggested: { genre: "Indie", mood: "Raw & honest" } },
  { id: "memory-i-cant-forget", theme: "A memory I can’t forget", tagline: "Return to one moment in vivid detail", starterThought: "There is a memory I return to without trying. I can still see the light, hear the room, and feel the exact second when something in me changed.", feelings: ["nostalgic", "bittersweet", "tender"], glyph: "◌", suggested: { genre: "Country", mood: "Cinematic" } },
  { id: "where-i-am", theme: "Where I am in life", tagline: "Take an honest snapshot of right now", starterThought: "I am somewhere between who I used to be and whoever I am becoming. Nothing feels completely settled, but I am beginning to recognize myself here.", feelings: ["overwhelmed", "hopeful", "peaceful"], glyph: "◎", suggested: { genre: "Lo-fi", mood: "Bittersweet" } },
  { id: "letting-go", theme: "Letting go", tagline: "Release something you have carried too long", starterThought: "I have been holding on to something I know I need to release. Part of me is afraid of who I am without it, but I can finally feel how heavy it has become.", feelings: ["bittersweet", "relieved", "free"], glyph: "↝", suggested: { genre: "Acoustic / Folk", mood: "Bittersweet" } },
  { id: "quiet-gratitude", theme: "Quiet gratitude", tagline: "Notice the beauty in an ordinary day", starterThought: "Nothing extraordinary happened today, and that is exactly what I want to remember: morning light, a familiar voice, and the calm of having enough for this moment.", feelings: ["grateful", "peaceful", "tender"], glyph: "✦", suggested: { genre: "Lo-fi", mood: "Peaceful" } },
  { id: "falling-for-someone", theme: "Falling for someone", tagline: "Capture the bright uncertainty of new love", starterThought: "I am falling for someone in all the small ways first—the messages I reread, the room changing when they arrive, and the hope I am almost afraid to name.", feelings: ["in love", "excited", "tender"], glyph: "♡", suggested: { genre: "R&B / Soul", mood: "Playful" } },
  { id: "finding-confidence", theme: "Finding my confidence", tagline: "Turn down doubt and hear your own voice", starterThought: "I spent too long making myself smaller so other people would feel comfortable. I am learning that confidence does not have to be loud to be real.", feelings: ["proud", "free", "hopeful"], glyph: "↑", suggested: { genre: "Rock", mood: "Uplifting" } },
  { id: "dream-still-chasing", theme: "A dream I’m still chasing", tagline: "Write toward the future you refuse to abandon", starterThought: "There is a dream I keep returning to even when it would be easier to call it unrealistic. I am not there yet, but I am still moving toward it.", feelings: ["hopeful", "excited", "proud"], glyph: "☆", suggested: { genre: "Electronic", mood: "Uplifting" } },
] as const;

export function getTemplate(id: string): Template | undefined {
  return TEMPLATES.find((template) => template.id === id);
}
